name: Auto Approve PRs with Markdown Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get PR Author
        id: get_pr_author
        run: echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Check if PR author is a collaborator in the repository
        id: check_user_role
        run: |
          USER=${{ env.PR_AUTHOR }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}

          # GitHub API call to check if the user is a collaborator (has read, write, or admin permissions)
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$OWNER/$REPO/collaborators/$USER/permission)

          # Check if the user has permissions (admin, write, or read)
          PERMISSION=$(echo $RESPONSE | jq -r .permission)
          
          if [[ "$PERMISSION" == "admin" || "$PERMISSION" == "write" || "$PERMISSION" == "read" ]]; then
            echo "role=collaborator" >> $GITHUB_ENV
            echo "The user $USER has $PERMISSION permission on the repository."
          else
            echo "role=none" >> $GITHUB_ENV
            echo "The user $USER does not have access to the repository."
          fi

      - name: Skip if the PR author is not a collaborator
        if: env.role == 'none'
        run: |
          echo "The PR author (${{ env.PR_AUTHOR }}) is not a collaborator in the repository. Skipping workflow."
          exit 0

      - name: Proceed if the user is a collaborator
        if: env.role == 'collaborator'
        run: echo "Proceeding because the PR author (${{ env.PR_AUTHOR }}) is a collaborator with repository access."
      - name: Get list of changed files
        id: changed_files
        run: |
          # Get a list of files changed in the pull request
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})"
          echo ${{github.event.pull_request.user_association}}
          
      - name: Check for non-Markdown files
        id: check_files
        run: |
          files="${{ steps.changed_files.outputs.files }}"
          
          # Filter files that are not .md or .mdx
          non_md_files=$(echo "$files" | grep -vE '\.md$|\.mdx$' || true)

          # Fail the step if there are any non-Markdown files
          if [ -n "$non_md_files" ]; then
            echo "Non-markdown files detected: $non_md_files"
            exit 1
          else
            echo "Only Markdown files detected."
          fi

      - name: Approve the PR if only Markdown files changed
        if: steps.check_files.outcome == 'success'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

